services:
  - type: web
    name: chattoeic-api
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000