[phases.build]
cmds = [
    "npx prisma generate --schema=prisma/schema.prisma",
    "npm run build"
]

[phases.start]
cmd = "npx prisma migrate deploy --schema=prisma/schema.prisma && npx tsx prisma/seed.ts && node dist/server.js"

[variables]
NODE_ENV = "production"